version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ~/docker/nginx/data:/data
      - ~/docker/nginx/letsencrypt:/etc/letsencrypt
